version: "3.9"

services:

    database:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'db'   
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'      
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - "./.mysql-data/db:/var/lib/mysql"
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 55

    nodeserver:
        build:
            context: ./node
        ports:
            - "3000:3000"
        volumes:
            - ./node:/usr/src/app
        tty: true
        depends_on:
            database:
                condition: service_healthy

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"